baseURL = "https://adams1.com/"
languageCode = "en-us"
title = "Adams1"
theme = "simple-news"
uglyURLs = true

[params]
  description = "barcode standards and technology"
  niche = "barcode standards and technology"
  founded_year = 2026

[markup.goldmark.renderer]
  unsafe = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5

[[menu.legal]]
  name = "About"
  url = "/about.html"
  weight = 10

[[menu.legal]]
  name = "Privacy Policy"
  url = "/privacy-policy.html"
  weight = 20

[[menu.legal]]
  name = "Disclaimer"
  url = "/disclaimer.html"
  weight = 30
